name: WEB API 


on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
 publish:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4

    - name: Setup .NET  
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

     
    - name: Restore
      run: dotnet restore LunaEdgeAssignment/LunaTask.Api/LunaTask.Api.sln
      
    - name: Build
      run: dotnet build LunaEdgeAssignment/LunaTask.Api/LunaTask.Api.sln --no-restore

    - name: Test
      run: dotnet test LunaEdgeAssignment/LunaTask.Api/LunaTask.Api.sln
      

      
   
    





  
